### ISSUE TITLE
slider does not work in windows/chrome

### ISSUE THREAD

**Issue by samyem** [JonComo/anim#8]
The "slide" command does not change the number value when dragging over it in windows 10/Chrome 70.

**Comment by catruge** [comment]
Did you use `slide: x` (x would be replaced with your variable name)?

**Comment by JonComo** [comment]
This appears to be working for me.

**Comment by SomanshArora** [comment]
slide Not working for me in any browser. i downloaded version 1.6.0 and 1.5.5 both and checked. also the "e" and "slide" are not hidden in presentation mode as shown in the youtube demo video. 
 
https://user-images.githubusercontent.com/72383918/143592523-244195d9-03b9-4e3c-a934-42c717eeb93c.mp4

**Comment by catruge** [comment]
@SomanshArora, I hadn't made a release in a while; I created one right now though (https://github.com/JonComo/anim/releases/tag/v2.0.0) in case you want to try it. The GitHub Pages site should always be up to date (https://joncomo.github.io/anim). `e:` was removed because textboxes now re-evaluate automatically when a variables they mention is modified. (The special variable `_frame` can be used for custom animations instead. See 'SPECIAL VALUES' at https://joncomo.github.io/anim if you are planning to create custom animations.) If you remove `e:` from `e:x=12`, `x` will be correctly initialised to `12`. Other than `e:` having to be removed from `e:graph(sin(x))`, the latter doesn't work because `graph` expects a function as argument. `sin(x)` is a value; if you are trying to plot a horizontal line at x-coordinate `x`, use `graph(_ |-> sin(x))` instead. (`|->` creates a lambda function, in this case with input `_` and output `sin(x)`. The function passed to `graph` must accept one parameter, which is the purpose of `_` before.)

The `slide:` text has not been kept since I started working on the project (after https://github.com/JonComo/anim/tree/e83bbc1b83a845f9e906e50b6629258ceadc5b1c), so I can't say when or why it was removed (@JonComo might know). Sorry about that :sweat_smile:.
